// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqwN9Y4mL_FP3B6aWNeYa97MqUAQ8K39Y',
    appId: '1:474041068870:web:2d3185bfbda22da42a4947',
    messagingSenderId: '474041068870',
    projectId: 'fetchat-df1d1',
    authDomain: 'fetchat-df1d1.firebaseapp.com',
    storageBucket: 'fetchat-df1d1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK76rGd2UdJwgga-_slS_4skWgNKZvfa8',
    appId: '1:474041068870:android:991f3aa13e4519dc2a4947',
    messagingSenderId: '474041068870',
    projectId: 'fetchat-df1d1',
    storageBucket: 'fetchat-df1d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ32y_TAeN72j-HlAMj6y5hubA3WldXSA',
    appId: '1:474041068870:ios:7571197418da96742a4947',
    messagingSenderId: '474041068870',
    projectId: 'fetchat-df1d1',
    storageBucket: 'fetchat-df1d1.appspot.com',
    iosBundleId: 'com.example.blueChatV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ32y_TAeN72j-HlAMj6y5hubA3WldXSA',
    appId: '1:474041068870:ios:7571197418da96742a4947',
    messagingSenderId: '474041068870',
    projectId: 'fetchat-df1d1',
    storageBucket: 'fetchat-df1d1.appspot.com',
    iosBundleId: 'com.example.blueChatV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqwN9Y4mL_FP3B6aWNeYa97MqUAQ8K39Y',
    appId: '1:474041068870:web:10fdc30c840483092a4947',
    messagingSenderId: '474041068870',
    projectId: 'fetchat-df1d1',
    authDomain: 'fetchat-df1d1.firebaseapp.com',
    storageBucket: 'fetchat-df1d1.appspot.com',
  );
}
